### ISSUE TITLE
Bug: Multiple Abilities/Ancient Trait

### ISSUE THREAD

**Issue by qwertystop** [PokemonTCG/pokemon-tcg-api#12]
Pokémon with both an Ability and an Ancient Trait (e.g. xy5-77, the Rhyperior in Primal Clash) have the Ability and Trait concatenated and the name of whichever one is first (probably the trait, but I don't know if the thing you get your data from has a guaranteed order) is lost. Suggest making a new field for Traits, I don't think there's any cards with two Abilities (though I'm not sure how I'd check) and there definitely aren't any with two Traits.

Also, technically the Trait is not an Ability and might need its own category? That problem is relatively easy to work around in most uses where the mechanical difference matters (manually parsing the Ability name to see if it's actually a Trait), but becomes slightly harder to work around when the Ability and Trait are stuck together.

**Comment by adback03** [comment]
Thanks for pointing this out! Not having the trait as it's own field was an oversight on my part. I'm out of town this weekend, but I'll works on a fix ASAP. I will be making the trait its own field, as you are right that they arent the same thing.

**Comment by adback03** [comment]
I have just released the fix for this, and "ancientTrait" is now its own field. Here is an example card that has both an ability and an ancient trait:

https://api.pokemontcg.io/v1/cards/xy6-46

You can also filter on ancientTrait:

https://api.pokemontcg.io/v1/cards?ancientTrait=evolution
https://api.pokemontcg.io/v1/cards?ancientTrait=evolution|growth
