### ISSUE TITLE
Kadabra's National Pokedex Number is incorrect

### ISSUE THREAD

**Issue by mmxxiii** [PokemonTCG/pokemon-tcg-api#25]
Nothing here:
https://api.pokemontcg.io/v1/cards?nationalPokedexNumber=64

Lists his dex number as 63 (which is Abra):
https://api.pokemontcg.io/v1/cards?name=Kadabra

You can see him mixed with the abra's here:
https://api.pokemontcg.io/v1/cards?nationalPokedexNumber=63

**Comment by adback03** [comment]
Thanks for pointing this out. I should hopefully be getting an update out tonight and I'll try to include a fix for this in the release.

**Comment by adback03** [comment]
This has been fixed in v1.7.2.

**Comment by mmxxiii** [comment]
Found a few more: http://api.pokemontcg.io/v1/cards?nationalPokedexNumber=47|141|233|474|601

47 - Parasect (merged with Paras #46)
141 - Kabutops (merged with Kabuto #140)
233 - Porygon2 (merged with Porygon #137)
474 - Porygon-Z (merged with Porygon #137)
601 - Klinklang (merged with Klink #599)

Also, as a side note, Magearna's National Pokedex Number is 801 (although it isn't listed on any of the cards she appears on).

P.S. - Thanks for all the updates. Hope my slew of issues isn't too bothersome.

**Comment by adback03** [comment]
Thanks for pointing this out - should be able to update this tonight. And don't worry about it, I wouldn't figure out a lot of these issues without people like you! I try to knock out the simple ones relatively quick. Some updates may take me a bit of time just because I have a few other projects I contribute to regularly, but I'm starting to look towards version 2 of this API now.
