### ISSUE TITLE
Card API: Page 0 returns the same result as Page 1

### ISSUE THREAD

**Issue by StrategistXIV** [PokemonTCG/pokemon-tcg-api#3]
This caused me some debugging time:P Maybe make page 0 return no result? Or to make page 1 be page 2?

**Comment by adback03** [comment]
This is because of the third party library Kaminari that I use to page the data. Here is the relevant bit of code: 

https://github.com/amatsuda/kaminari/blob/master/lib/kaminari/models/active_record_model_extension.rb

    default_per_page * ((num = num.to_i - 1) < 0 ? 0 : num)

Pretty much, it looks like Kaminari will just make the offset 0 if it is less than 0. So if your page is 0, it calculates the offset as -1, which is invalid.

I will look into making page 0 return no results to limit the confusion.

Thanks!

**Comment by StrategistXIV** [comment]
No probs! Helping to enhance the platform is something I will gladly do:P

**Comment by adback03** [comment]
This has been fixed and released with v1.2.0

**Comment by StrategistXIV** [comment]
Nice! Good work(Y)
