### ISSUE TITLE
EX Subtype blocks Basic, Stage 1, Stage 2

### ISSUE THREAD

**Issue by doeiqts** [PokemonTCG/pokemon-tcg-api#40]
Since EX (and now GX) Pokemon can be Basic or Evolution Pokemon, it would be nice to still have the subtype of a Pokemon show whether it's Basic, Stage 1, or Stage 2. I'm not sure whether it would fit better with your API to allow a card to have multiple subtypes to accomplish this or to instead just add a boolean field "isEX" or something like that that can be checked and just remove EX from the subtypes.

**Comment by mmxxiii** [comment]
I was thinking the stage could be included with the GX subtype e.g. `"subtype":"Stage 1 GX"` in the current version of the API (v1). Although making subtype an array would be good option for a future version of the API e.g. `"subtypes": ["Stage 1","GX"]`. Or, better yet, break stage out into it's own field and use an array for subtype, as that would allow for a possible future where GX (or EX) is combined with another as yet unknown subtype, e.g. `"stage":"Stage 1","subtypes":["GX","Unknown Future Subtype"]`.

**Comment by doeiqts** [comment]
I really like the idea of having "stage" be its own field from "subtype".

**Comment by Hamatti** [comment]
Hey @adback03 ! I know this is an old issue but I just ran into this today. I'd like to build a small app that provides information about a deck (like if it's legal and what are it's odds for starting with a certain Pokemon, odds of mulligans etc) but since I cannot know which GX's are basic and which are not, I can't.

Any plans for making the enhancement happen in the near future or do you have a good workaround that I could use?

**Comment by adback03** [comment]
Subtypes is now an array in V2 of the API, so a card can now support multiple types (Like GX and Basic)
