### ISSUE TITLE
Evolves To Field

### ISSUE THREAD

**Issue by glinesbdev** [PokemonTCG/pokemon-tcg-api#51]
I think it would be awesome to have an _evolvesTo_ field in addition to the _evolvesFrom_ field in the API. I may be missing something but does something like this already exist? I can see that the [Pokemon](http://www.pokemon.com/us/pokedex/dartrix) website shows this.

**Comment by mmxxiii** [comment]
evolvesTo could be a problem because of split evolution lines (ponder eevee for a moment).
The pokemon that a card can evolve from is printed on the cards and appears in the pokemon card database on pokemon.com, whereas pokemon that it evolves to isn't.
Finding pokemon that another evolves to is pretty easy using evolvesFrom. If you want to know what eevee evolves to, for example, just do a search for "evolvesFrom=eevee".

**Comment by glinesbdev** [comment]
Okay awesome. Yes I can see how I can make that work by looking up Pokémon that evolve from the current one and the next one and so on until it's a false statement. Thanks a lot for your feedback.
