### ISSUE TITLE
Feature Request: Pokemon Endpoint?

### ISSUE THREAD

**Issue by cssagogo** [PokemonTCG/pokemon-tcg-api#80]
Would be cool to have a /pokemon endpoint that returned a list of unique pokemon names including their national pokedex number.  Bonus points for returning the rest of the pokedex info as well...

https://www.pokemon.com/us/pokedex/pikachu

I could then call this to generate a list of pokemon by pokedex number and click through to view all the cards for that pokemon.

**Comment by r0adkll** [comment]
I feel as if this is outside the scope of this API since it focuses on the Trading Card Game aspect of Pokémon. You can already search by `name` or `nationalPokedexNumber` to retrieve the cards of a specific Pokémon and you would probably be better off using an API like https://pokeapi.co/ to retrieve the Pokedex information.

**Comment by adback03** [comment]
I agree that providing pokemon information is not within the scope of this API.
