### ISSUE TITLE
Not all cards come in search by setCode|set

### ISSUE THREAD

**Issue by LucasMessiasPG** [PokemonTCG/pokemon-tcg-api#9]
Url ex: https://api.pokemontcg.io/v1/cards?setCode=bw3
take only 100 cards but have 102 cards in this set

**Comment by adback03** [comment]
This is because all results are paginated by default with a pageSize of 100. Too see the remaining two results, you can look at the next page:

https://api.pokemontcg.io/v1/cards?setCode=bw3&page=2

To see more examples, check the docs: http://docs.pokemontcg.io/#get-all-cards

Let me know if you have any other issues!
